# Project information
site_name: "Git & GitHub: Professional Software Project Management"
site_url: https://hei1sme.github.io/git-github-book/
site_description: Comprehensive guide on using Git & GitHub for professional software development and teamwork.
docs_dir: content

# Repository information
repo_url: https://github.com/hei1sme/git-github-book
repo_name: hei1sme/git-github-book

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs # Top level navigation as tabs
    - navigation.sections # Expandable sections in sidebar
    - navigation.instant # Faster page loading
    - navigation.top # Back to top button
    - search.suggest # Search suggestions
    - search.highlight # Highlight search results
    - content.tabs.link # Linkable tabs in content
    - content.code.annotate # Code annotations
    - content.code.copy # Copy button for code blocks
  palette: 
    primary: 'black'
    accent: 'purple'
  language: en 
  # customize favicon, logo, etc. here if needed
  
nav:
  - "Home": index.md
  - "Introduction to the Reader": 00-introduction-to-the-reader.md
  - "Table of Contents": 01-table-of-contents.md
  - "Chapters":
    - "Chapter 1: Introduction to Version Control, Git, and GitHub": 02-chapter-01-introduction-to-git.md
    - "Chapter 2: Git Basics - Getting Started with Your First Repository": 03-chapter-02-git-basics.md
    - "Chapter 3: Exploring GitHub Repository Anatomy": 04-chapter-03-github-anatomy.md
    - "Chapter 4: Branching and Merging - Working on Different Ideas": 05-chapter-04-branching-merging.md
    - "Chapter 5: Collaborative Workflows with GitHub": 06-chapter-05-collaborative-workflows.md
    - "Chapter 6: Advanced Git Concepts and Commands": 07-chapter-06-advanced-git.md
    - "Chapter 7: Automating Workflows with GitHub": 08-chapter-07-automating-with-github.md
    - "Chapter 8: Managing Permissions, Security, and Repository Settings": 09-chapter-08-permissions-security.md
    - "Chapter 9: Best Practices for Professional Git and GitHub Usage": 10-chapter-09-best-practices.md
    - "Chapter 10: Troubleshooting Common Issues and Debugging": 11-chapter-10-troubleshooting.md
  - "Appendices":
    - "Appendix A: Glossary of Git and GitHub Terms": 12-appendix-a-glossary.md
    - "Appendix B: Useful Git Commands Reference": 13-appendix-b-commands-reference.md
    - "Appendix C: Setting up SSH Keys for GitHub": 14-appendix-c-ssh-keys.md
    - "Appendix D: Further Resources": 15-appendix-d-further-resources.md

# Markdown extensions for better formatting
markdown_extensions:
  - admonition 
  - pymdownx.details 
  - pymdownx.superfences 
  - attr_list 
  - footnotes 
  - pymdownx.highlight: 
      anchor_linenums: true
  - pymdownx.tabbed: 
      alternate_style: true
  - toc:
      permalink: true

# Plugins
plugins:
  - search 
  # - git-revision-date-localized # Optional: show last update date on pages (requires git)

# Extra options (optional)
extra:
  social: # Links to your social media/GitHub profile
    - icon: fontawesome/brands/github
      link: https://github.com/hei1sme
